
DELETE http://localhost:8080/tarefas/fd970eaa-efb2-4abf-8e0c-1976d40d73ea HTTP/1.1
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYwOGYyNDU3LTg4YWItNGQyNS04ZGJkLTljMzNlY2VhY2I3NCIsIm5vbWUiOiJHYWJyaWVsIiwidXNlcm5hbWUiOiJnYWJyaWVsIiwiY3JpYWRvRW0iOiIyMDI0LTAxLTEyVDIxOjE0OjM1LjM1N1oiLCJpYXQiOjE3MDUwOTQwNzUsImV4cCI6MTcwNTA5NzY3NX0.ndUrHrrAHRoBYMYIkrBqU-pLUJ76CkmGfHniLPqpg9c